### ISSUE TITLE
Interpreting stats

### ISSUE THREAD

**Issue by marcin-github** [akiradeveloper/dm-writeboost-tools#16]
Hi again!
I would like to ask what `write=1 & hit=1` means?
Example:
cursor pos              = 52040677
\# of cache blocks       = 91033346
\# of segments           = 716798
current id              = 1126568
last flushed id         = 1126567
last writeback id       = 487778
\# of dirty cache blocks = 66562932
\# of partial flushes    = 38108
write? hit? on_buffer? fullsize?
0      0    0          0         1
0      0    0          1         205034196
0      0    1          0         0
0      0    1          1         0
0      1    0          0         0
0      1    0          1         1681415
0      1    1          0         0
0      1    1          1         0
1      0    0          0         0
1      0    0          1         128200323
1      0    1          0         0
1      0    1          1         0
1      1    0          0         0
1      1    0          1         498264
1      1    1          0         0
1      1    1          1         67

What line `1      1    0          1         498264` means?

**Comment by akiradeveloper** [comment]
* 0 = false, 1 = true
* write? = was the IO write?
* hit? = was the IO cache-hit?
* on_buffer? = if so, hit on the RAM buffer?
* fullsize? = was the IO 4KB?

then 1 1 0 1 498264 means "4KB writes hit on the caching device 498264 times"

**Comment by marcin-github** [comment]
Ok but I don't get how write can or can not hit caching device? All writes should go to caching device.

**Comment by akiradeveloper** [comment]
The stat is just the result of cache lookup and all writes first go to RAM buffer but caching device.

**Comment by marcin-github** [comment]
So there were  `128200323` blocks written to cache and it hit the RAM buffer. Then the blocks was moved to SSD and it genereted ` 498264` blocks writes to SSD?

**Comment by akiradeveloper** [comment]
No. You completely misunderstood. I don't want to explain any more.

**Comment by marcin-github** [comment]
Thanks for help.

**Comment by akiradeveloper** [comment]
"it hit the RAM buffer" how do you think so? don't go crazy
