### ISSUE TITLE
tests in docker and Github Actions

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/dm-writeboost-tools#20]
Since Rust is evolving the source code should be changed accordingly. Basic regression test is ok but should be written and environment should be built in docker.

**Comment by onlyjob** [comment]
I recommend to avoid docker and instead use its superiour successor: libpod/Podman.

**Comment by akiradeveloper** [comment]
That seems the best choice as of now but unfortunately I couldn't succeed to install and run podman in my Mac environment. After podman becomes as popular as docker, I will try later.

**Comment by akiradeveloper** [comment]
done
