### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by kazuhisya** [akiradeveloper/dm-writeboost-tools#3]
Could you add LICENSE file?
I plan to make this package, but it need define a license.

ref: kazuhisya/dm-writeboost-rpm/issues/7

**Comment by akiradeveloper** [comment]
@kazuhisya I added a LICENSE file but hold on until the software is released. It's still experimental state which lacks two commands to implement. Making the build script by your side is ok but releasing it as binary is too early. I will complete this by the release of writeboost 2.2.7

**Comment by kazuhisya** [comment]
Hi, @akiradeveloper
>  It's still experimental state which lacks two commands to implement. Making the build script by your side is ok but releasing it as binary is too early.

OK, I understood.
I will release the binary when you added git tag(release tag) in this repository.

Thank you for your quick response!
